using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YoutubeExplode;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.Streams;
using YoutubeExplode.Converter;

using PremiumYoutubeDownloader.Models;

namespace PremiumYoutubeDownloader.Services;

public class VideoDownloaderService
{
    private readonly YoutubeClient _youtube;

    public VideoDownloaderService()
    {
        _youtube = new YoutubeClient();
    }

    public async Task<Video> GetVideoDetailsAsync(string url)
    {
        return await _youtube.Videos.GetAsync(url);
    }

    public async Task<string?> DownloadSubtitlesAsync(string url, string filePath, string languageCode = "en")
    {
        try
        {
            var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(url);
            var track = manifest.Tracks.FirstOrDefault(t => t.Language.Code.StartsWith(languageCode, StringComparison.OrdinalIgnoreCase));
            if (track == null && languageCode.Equals("auto", StringComparison.OrdinalIgnoreCase)) 
                track = manifest.Tracks.FirstOrDefault(t => t.IsAutoGenerated);
            if (track == null) track = manifest.Tracks.FirstOrDefault();

            if (track != null)
            {
                await _youtube.Videos.ClosedCaptions.DownloadAsync(track, filePath);
                return filePath;
            }
        }
        catch { /* Subtitles not available or failed */ }
        return null;
    }

    public async Task<List<StreamQualityOption>> GetAvailableQualitiesAsync(string videoUrl)
    {
        var manifest = await _youtube.Videos.Streams.GetManifestAsync(videoUrl);
        var options = new List<StreamQualityOption>();

        // Native Muxed Streams (Video + Audio)
        var muxedStreams = manifest.GetMuxedStreams()
            .OrderByDescending(s => s.VideoResolution.Area)
            .GroupBy(s => s.VideoResolution.Height)
            .Select(g => g.OrderByDescending(s => s.VideoCodec).First()); // Prioritize newer codecs if same res

        foreach (var stream in muxedStreams)
        {
            options.Add(new StreamQualityOption
            {
                DisplayName = $"{stream.VideoResolution.Height}p (Native {stream.Container.Name}) - {stream.VideoCodec}",
                VideoStream = stream,
                AudioStream = stream,
                RequiresFfmpeg = false
            });
        }

        // Adaptive Video-Only Streams (requires FFmpeg to mux with audio)
        var bestAudio = manifest.GetAudioOnlyStreams().GetWithHighestBitrate();
        var adaptiveVideos = manifest.GetVideoOnlyStreams()
            .Where(s => s.VideoResolution.Height > muxedStreams.FirstOrDefault()?.VideoResolution.Height) // Only higher res than native
            .OrderByDescending(s => s.VideoResolution.Area)
            .GroupBy(s => s.VideoResolution.Height)
            .Select(g => g.First());

        foreach (var stream in adaptiveVideos)
        {
            options.Add(new StreamQualityOption
            {
                DisplayName = $"{stream.VideoResolution.Height}p (Requires FFmpeg)",
                VideoStream = stream,
                AudioStream = bestAudio,
                RequiresFfmpeg = true
            });
        }

        // Audio-Only Streams
        var audioStreams = manifest.GetAudioOnlyStreams()
            .OrderByDescending(s => s.Bitrate)
            .GroupBy(s => s.Container.Name)
            .Select(g => g.First());

        foreach (var stream in audioStreams)
        {
            options.Add(new StreamQualityOption
            {
                DisplayName = $"Audio Only ({stream.Container.Name} - {stream.Bitrate.KiloBitsPerSecond:F0} kbps)",
                VideoStream = null,
                AudioStream = stream,
                RequiresFfmpeg = false
            });
        }

        return options;
    }

    public async Task DownloadAsync(StreamQualityOption option, string outputFilePath, IProgress<double>? progress = null, CancellationToken cancellationToken = default)
    {
        if (option.RequiresFfmpeg && option.VideoStream != null && option.AudioStream != null)
        {
            // Use YoutubeExplode.Converter to mux video and audio together
            var streamInfos = new IStreamInfo[] { option.VideoStream, option.AudioStream };
            await _youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(outputFilePath).Build(), progress, cancellationToken);
        }
        else if (option.AudioStream != null && option.VideoStream == null)
        {
            if (outputFilePath.EndsWith(".mp3", StringComparison.OrdinalIgnoreCase))
            {
                var streamInfos = new IStreamInfo[] { option.AudioStream };
                await _youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(outputFilePath).Build(), progress, cancellationToken);
            }
            else
            {
                await _youtube.Videos.Streams.DownloadAsync(option.AudioStream, outputFilePath, progress, cancellationToken);
            }
        }
        else if (option.VideoStream != null)
        {
            await _youtube.Videos.Streams.DownloadAsync(option.VideoStream, outputFilePath, progress, cancellationToken);
        }
        else if (option.AudioStream != null)
        {
            await _youtube.Videos.Streams.DownloadAsync(option.AudioStream, outputFilePath, progress, cancellationToken);
        }
    }
}
